version: '3'

services:

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: game-client
    ports:
      - 80:80
    depends_on: 
      - server
  
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: game-server
    ports: 
      - 5000:5000
                